# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yarn_spinner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yarn_spinner.proto',
  package='Yarn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12yarn_spinner.proto\x12\x04Yarn\"z\n\x07Program\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05nodes\x18\x02 \x03(\x0b\x32\x18.Yarn.Program.NodesEntry\x1a\x38\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Yarn.Node:\x02\x38\x01\"\xbe\x01\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x0cinstructions\x18\x02 \x03(\x0b\x32\x11.Yarn.Instruction\x12&\n\x06labels\x18\x03 \x03(\x0b\x32\x16.Yarn.Node.LabelsEntry\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x1a\n\x12sourceTextStringID\x18\x05 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xe4\x02\n\x0bInstruction\x12(\n\x06opcode\x18\x01 \x01(\x0e\x32\x18.Yarn.Instruction.OpCode\x12\x1f\n\x08operands\x18\x02 \x03(\x0b\x32\r.Yarn.Operand\"\x89\x02\n\x06OpCode\x12\x0b\n\x07JUMP_TO\x10\x00\x12\x08\n\x04JUMP\x10\x01\x12\x0c\n\x08RUN_LINE\x10\x02\x12\x0f\n\x0bRUN_COMMAND\x10\x03\x12\x0e\n\nADD_OPTION\x10\x04\x12\x10\n\x0cSHOW_OPTIONS\x10\x05\x12\x0f\n\x0bPUSH_STRING\x10\x06\x12\x0e\n\nPUSH_FLOAT\x10\x07\x12\r\n\tPUSH_BOOL\x10\x08\x12\r\n\tPUSH_NULL\x10\t\x12\x11\n\rJUMP_IF_FALSE\x10\n\x12\x07\n\x03POP\x10\x0b\x12\r\n\tCALL_FUNC\x10\x0c\x12\x11\n\rPUSH_VARIABLE\x10\r\x12\x12\n\x0eSTORE_VARIABLE\x10\x0e\x12\x08\n\x04STOP\x10\x0f\x12\x0c\n\x08RUN_NODE\x10\x10\"W\n\x07Operand\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x42\x07\n\x05valueb\x06proto3'
)



_INSTRUCTION_OPCODE = _descriptor.EnumDescriptor(
  name='OpCode',
  full_name='Yarn.Instruction.OpCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JUMP_TO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUMP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUN_LINE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUN_COMMAND', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADD_OPTION', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHOW_OPTIONS', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUSH_STRING', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUSH_FLOAT', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUSH_BOOL', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUSH_NULL', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUMP_IF_FALSE', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POP', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CALL_FUNC', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUSH_VARIABLE', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STORE_VARIABLE', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUN_NODE', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=437,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_INSTRUCTION_OPCODE)


_PROGRAM_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='Yarn.Program.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Yarn.Program.NodesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Yarn.Program.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=150,
)

_PROGRAM = _descriptor.Descriptor(
  name='Program',
  full_name='Yarn.Program',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Yarn.Program.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Yarn.Program.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROGRAM_NODESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=150,
)


_NODE_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='Yarn.Node.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Yarn.Node.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Yarn.Node.LabelsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=343,
)

_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='Yarn.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Yarn.Node.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instructions', full_name='Yarn.Node.instructions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labels', full_name='Yarn.Node.labels', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Yarn.Node.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sourceTextStringID', full_name='Yarn.Node.sourceTextStringID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NODE_LABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=343,
)


_INSTRUCTION = _descriptor.Descriptor(
  name='Instruction',
  full_name='Yarn.Instruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opcode', full_name='Yarn.Instruction.opcode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operands', full_name='Yarn.Instruction.operands', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSTRUCTION_OPCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=702,
)


_OPERAND = _descriptor.Descriptor(
  name='Operand',
  full_name='Yarn.Operand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='Yarn.Operand.string_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='Yarn.Operand.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='Yarn.Operand.float_value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='Yarn.Operand.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=704,
  serialized_end=791,
)

_PROGRAM_NODESENTRY.fields_by_name['value'].message_type = _NODE
_PROGRAM_NODESENTRY.containing_type = _PROGRAM
_PROGRAM.fields_by_name['nodes'].message_type = _PROGRAM_NODESENTRY
_NODE_LABELSENTRY.containing_type = _NODE
_NODE.fields_by_name['instructions'].message_type = _INSTRUCTION
_NODE.fields_by_name['labels'].message_type = _NODE_LABELSENTRY
_INSTRUCTION.fields_by_name['opcode'].enum_type = _INSTRUCTION_OPCODE
_INSTRUCTION.fields_by_name['operands'].message_type = _OPERAND
_INSTRUCTION_OPCODE.containing_type = _INSTRUCTION
_OPERAND.oneofs_by_name['value'].fields.append(
  _OPERAND.fields_by_name['string_value'])
_OPERAND.fields_by_name['string_value'].containing_oneof = _OPERAND.oneofs_by_name['value']
_OPERAND.oneofs_by_name['value'].fields.append(
  _OPERAND.fields_by_name['bool_value'])
_OPERAND.fields_by_name['bool_value'].containing_oneof = _OPERAND.oneofs_by_name['value']
_OPERAND.oneofs_by_name['value'].fields.append(
  _OPERAND.fields_by_name['float_value'])
_OPERAND.fields_by_name['float_value'].containing_oneof = _OPERAND.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Program'] = _PROGRAM
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Instruction'] = _INSTRUCTION
DESCRIPTOR.message_types_by_name['Operand'] = _OPERAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Program = _reflection.GeneratedProtocolMessageType('Program', (_message.Message,), {

  'NodesEntry' : _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROGRAM_NODESENTRY,
    '__module__' : 'yarn_spinner_pb2'
    # @@protoc_insertion_point(class_scope:Yarn.Program.NodesEntry)
    })
  ,
  'DESCRIPTOR' : _PROGRAM,
  '__module__' : 'yarn_spinner_pb2'
  # @@protoc_insertion_point(class_scope:Yarn.Program)
  })
_sym_db.RegisterMessage(Program)
_sym_db.RegisterMessage(Program.NodesEntry)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _NODE_LABELSENTRY,
    '__module__' : 'yarn_spinner_pb2'
    # @@protoc_insertion_point(class_scope:Yarn.Node.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : _NODE,
  '__module__' : 'yarn_spinner_pb2'
  # @@protoc_insertion_point(class_scope:Yarn.Node)
  })
_sym_db.RegisterMessage(Node)
_sym_db.RegisterMessage(Node.LabelsEntry)

Instruction = _reflection.GeneratedProtocolMessageType('Instruction', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTION,
  '__module__' : 'yarn_spinner_pb2'
  # @@protoc_insertion_point(class_scope:Yarn.Instruction)
  })
_sym_db.RegisterMessage(Instruction)

Operand = _reflection.GeneratedProtocolMessageType('Operand', (_message.Message,), {
  'DESCRIPTOR' : _OPERAND,
  '__module__' : 'yarn_spinner_pb2'
  # @@protoc_insertion_point(class_scope:Yarn.Operand)
  })
_sym_db.RegisterMessage(Operand)


_PROGRAM_NODESENTRY._options = None
_NODE_LABELSENTRY._options = None
# @@protoc_insertion_point(module_scope)
